[build]
  command = "./build-netlify.sh"
  publish = "dist"
  functions = "dist/.netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200